# Generated by Django 5.1.4 on 2024-02-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
