# Generated by Django 5.1.4 on 2024-02-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(help_text="Укажите время", verbose_name="Время"),
        ),
    ]
