# Generated by Django 5.1.4 on 2025-01-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Выберете дату и время начала привычки",
                        null=True,
                        verbose_name="Время начала выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Опишите действие вашей привычки", max_length=255, verbose_name="Действие привычки"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, help_text="Привычка является приятной", verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("every minutes", "каждую минуту"),
                            ("every day", "каждый день"),
                            ("every other day", "через день"),
                            ("every three days", "раз в 3 дня"),
                            ("every four days", "раз в 4 дня"),
                            ("every five days", "раз в 5 дней"),
                            ("every six days", "раз в 6 дней"),
                            ("every week", "раз в неделю"),
                        ],
                        default="every day",
                        help_text="Выберите периодичность выполнения привычки",
                        max_length=16,
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите предположительное время выполнения привычки в минутах",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Опубликовать для общего доступа", verbose_name="Общий доступ"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберете связанную приятную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
